apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: andylmotta
    provider: github
    repository: skiapp
  name: andylmotta-skiapp
spec:
  description: Imported application for andylmotta/skiapp
  httpCloneURL: https://github.com/andylmotta/skiapp.git
  org: andylmotta
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: skiapp
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/andylmotta/skiapp.git
